CREATE TABLE `Landlord` (
  `userID` int(11) NOT NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `landlordIDFK` FOREIGN KEY (`userID`) REFERENCES `Posting` (`landlordID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `userIDFK2` FOREIGN KEY (`userID`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
