CREATE TABLE `Students` (
  `userID` int(11) NOT NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `userIDFK` FOREIGN KEY (`userID`) REFERENCES `Users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
